---
title: "EM practice"
output: html_document
date: "2025-03-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(mvtnorm)

Mu1 = c(1,1)
Mu2 = c(7,7)
Sigma1 = matrix(c(2, 1, 1, 1), 2,2)
Sigma2 = matrix(c(2, 2, 2, 5), 2,2)

pi = 1/3
n = 300

set.seed(2)
data = matrix(0, n, 2)
z = rep(0,n)
for (i in 1:n){
  z[i] = rbinom(1,1,pi)
  if (z[i] ==1){
    data[i,] = rmvnorm(1, Mu1,Sigma1)
  }else{
    data[i,] = rmvnorm(1, Mu2,Sigma2)
  }
}

to.plot = data.frame(x = data[,1], 
                  y = data[,2], 
                  class =  z)
ggplot(to.plot)+ aes(x, y, color = class)+
  geom_point()+geom_density_2d()
```

```{r}
#initial values
pi = 0.5
mu1 = data[1,]
mu2 = data[150,]
sigma1 = cov(data)
sigma2 = cov(data)
```

```{r}
# EM algorithm
Alpha = NULL # γ en el pdf
phi1 = dmvnorm(data, mu1, sigma1) # φ1 en el pdf
phi2 = dmvnorm(data, mu2, sigma2) # φ1 en el pdf

alpha = (phi1*pi)/(phi1*pi + phi2*(1-pi))
l = sum(alpha*log(pi) + (1-alpha)*log(1-pi)) + sum(alpha*log(phi1) + (1-alpha)*log(phi2))
n_iter=50
for (i in 1:n_iter){
  # Expectation step
  alpha = (pi*phi1)/(pi*phi1+(1-pi)*phi2) # γ en el pdf
  Alpha = cbind(Alpha, alpha)
  
  # Maximization step
  mu1 =apply(alpha*data/sum(alpha),2,sum)
  mu2 =apply((1-alpha)*data/sum(1-alpha),2,sum)
  
  sigma1 = cov.wt(data, wt = alpha, method = "ML")$cov
  sigma2 = cov.wt(data, wt = 1-alpha, method = "ML")$cov
  pi = mean(alpha)
  
  phi1 = dmvnorm(data, mu1, sigma1)
  phi2 = dmvnorm(data, mu2, sigma2)
}

```


```{r}
#library(SDMTools)

# EM algorithm
Alpha = NULL
tol = 10^-2
iter = 0
Q = 0
phi1 = dmvnorm(data, mu1, sigma1) # density at each point data
phi2 = dmvnorm(data, mu2, sigma2)
Q_ = sum(log(pi)+log(phi1)) + sum(log(pi)+log(phi2)) # this should be the log likelihood expression

#Q_ = sum()

while (abs(Q-Q_)>=tol) {
  
  iter = iter+1
  Q = Q_
  
  # Expectation step 
  alpha = pi*phi1/(pi*phi1+(1-pi)*phi2)
  Alpha = cbind(Alpha, alpha)
  
  # Maximization step
  mu1 = apply(data, 2, function(col) wt.mean(col, alpha))
  mu2 = apply(data, 2, function(col) wt.mean(col, 1-alpha))
  sigma1 = cov.wt(data, wt = alpha, method = "ML")$cov
  sigma2 = cov.wt(data, wt = 1-alpha, method = "ML")$cov
  pi = mean(alpha)
  
  phi1 = dmvnorm(data, mu1, sigma1)
  phi2 = dmvnorm(data, mu2, sigma2)
  Q_ = sum(log(pi)+log(phi1)) +
    sum(log(pi)+log(phi2))
}
```


